### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by samcfinan** [kwhitley/itty-router-extras#9]
Hi there, are there any plans to introduce TS type definitions? I think the router is a cool project and I'd love to contribute.

**Comment by hmnd** [comment]
[@types/itty-router-extras](https://www.npmjs.com/package/@types/itty-router-extras) is now live :)

**Comment by kwhitley** [comment]
Awesome!!!  I'm playing catch up (life issues the last few months), and just gave itty-router the TLC it needed, so this one is next :)

Great work on the @types entry! 🏅

**Comment by kwhitley** [comment]
> Hi there, are there any plans to introduce TS type definitions? I think the router is a cool project and I'd love to contribute.

Absolutely, and a @types definition is definitely a great start - but ultimately I would probably like this entire library to be rewritten in TS... it's a pretty ideal use-case, compared to the code-golfed itty-router, which absolutely wouldn't benefit from it.  This will hopefully be in the works before long (or if some amazing soul beats me to it!)

**Comment by hmnd** [comment]
@kwhitley Converting this library to TS would be great! I'll close #14 since I think the @types entry should suffice until then. Maybe I'll take up converting it if I get some spare time ;)

**Comment by kwhitley** [comment]
Closing this because that's exactly what's happening at https://github.com/kwhitley/itty-router/pull/121 :)

Hang in there!
